module.exports = {
  // authentication
  SOCKET_AUTH_ERROR: 'SOCKET_AUTH_ERROR',
  // library
  SONG_UPDATE: 'library/SONG_UPDATE',
  LIBRARY_FILTER_STRING: 'library/FILTER_KEYWORD',
  LIBRARY_FILTER_STRING_RESET: 'library/FILTER_KEYWORD_CLEAR',
  LIBRARY_FILTER_TOGGLE_STARRED: 'library/TOGGLE_FILTER_STARRED',
  TOGGLE_ARTIST_EXPANDED: 'library/TOGGLE_ARTIST_EXPANDED',
  TOGGLE_ARTIST_RESULT_EXPANDED: 'library/TOGGLE_ARTIST_RESULT_EXPANDED',
  SCROLL_ARTISTS: 'library/SCROLL_ARTISTS',
  LIBRARY_SONG_INFO_REQUEST: 'library/SONG_INFO_REQUEST',
  LIBRARY_SONG_INFO_CLOSE: 'library/SONG_INFO_CLOSE',
  // media
  LIBRARY_PUSH: 'library/PUSH',
  LIBRARY_PUSH_SONG: 'library/PUSH_SONG',
  // queue
  QUEUE_ADD: 'server/QUEUE_ADD',
  QUEUE_REMOVE: 'server/QUEUE_REMOVE',
  QUEUE_PUSH: 'queue/QUEUE_PUSH',
  // player command requests (clients -> server)
  REQUEST_PLAYER_PLAY: 'server/REQUEST_PLAYER_PLAY',
  REQUEST_PLAYER_PAUSE: 'server/REQUEST_PLAYER_PAUSE',
  REQUEST_PLAYER_NEXT: 'server/REQUEST_PLAYER_NEXT',
  REQUEST_PLAYER_VOLUME: 'server/REQUEST_PLAYER_VOLUME',
  // player commands (server -> player)
  PLAYER_NEXT: 'player/NEXT',
  PLAYER_PAUSE: 'player/PAUSE',
  PLAYER_PLAY: 'player/PLAY',
  PLAYER_VOLUME: 'player/VOLUME',
  // player -> server -> clients
  PLAYER_STATUS: 'status/PLAYER_STATUS',
  PLAYER_ERROR: 'status/PLAYER_ERROR',
  PLAYER_LEAVE: 'status/PLAYER_LEAVE',
  // to room (player -> server -> clients)
  EMIT_PLAYER_STATUS: 'server/EMIT_PLAYER_STATUS',
  EMIT_PLAYER_ERROR: 'server/EMIT_PLAYER_ERROR',
  EMIT_PLAYER_LEAVE:  'server/EMIT_PLAYER_LEAVE',
  // player informational
  PLAYER_MEDIA_REQUEST: 'player/MEDIA_REQUEST',
  PLAYER_MEDIA_REQUEST_SUCCESS: 'player/MEDIA_REQUEST_SUCCESS',
  PLAYER_MEDIA_REQUEST_ERROR: 'player/MEDIA_REQUEST_ERROR',
  // user
  SONG_TOGGLE_STARRED: 'server/SONG_TOGGLE_STARRED',
  LOGIN: 'user/LOGIN',
  LOGOUT: 'user/LOGOUT',
  CREATE: 'user/CREATE',
  UPDATE: 'user/UPDATE',
  GET_ROOMS: 'user/GET_ROOMS',
  ROOM_UPDATE: 'room/UPDATE',
  ROOM_CREATE: 'room/CREATE',
  ROOM_REMOVE: 'room/REMOVE',
  ROOM_EDITOR_OPEN: 'room/EDITOR_OPEN',
  ROOM_EDITOR_CLOSE: 'room/EDITOR_CLOSE',
  // misc
  _SUCCESS: '_SUCCESS',
  _ERROR: '_ERROR',
  // prefs
  PREFS_REQUEST: 'prefs/REQUEST',
  PREFS_SET: 'prefs/SET',
  PREFS_RECEIVE: 'prefs/RECEIVE',
  PREFS_REQUEST_SCAN: 'prefs/REQUEST_SCAN',
  PREFS_REQUEST_SCAN_CANCEL: 'prefs/REQUEST_SCAN_CANCEL',
  PREFS_SCAN_STATUS: 'prefs/SCAN_STATUS',
  // ui
  HEADER_HEIGHT_CHANGE: 'ui/HEADER_HEIGHT_CHANGE',
  FOOTER_HEIGHT_CHANGE: 'ui/FOOTER_HEIGHT_CHANGE',
  SHOW_ERROR_MESSAGE: 'ui/SHOW_ERROR_MESSAGE',
  CLEAR_ERROR_MESSAGE: 'ui/CLEAR_ERROR_MESSAGE',
}
