module.exports = {
  // authentication
  SOCKET_AUTH_ERROR: 'SOCKET_AUTH_ERROR',
  // library
  SONG_UPDATE: 'library/SONG_UPDATE',
  LIBRARY_SEARCH: 'library/SEARCH',
  LIBRARY_CHANGE_VIEW: 'library/LIBRARY_CHANGE_VIEW',
  TOGGLE_ARTIST_EXPANDED: 'library/TOGGLE_ARTIST_EXPANDED',
  // media
  MEDIA_PUSH: 'media/MEDIA_PUSH',
  // queue
  QUEUE_ADD: 'server/QUEUE_ADD',
  QUEUE_REMOVE: 'server/QUEUE_REMOVE',
  QUEUE_PUSH: 'queue/QUEUE_PUSH',
  // player command requests (clients -> server)
  REQUEST_PLAYER_PLAY: 'server/REQUEST_PLAYER_PLAY',
  REQUEST_PLAYER_PAUSE: 'server/REQUEST_PLAYER_PAUSE',
  REQUEST_PLAYER_NEXT: 'server/REQUEST_PLAYER_NEXT',
  REQUEST_PLAYER_VOLUME: 'server/REQUEST_PLAYER_VOLUME',
  // player commands (server -> player)
  PLAYER_NEXT: 'player/NEXT',
  PLAYER_PAUSE: 'player/PAUSE',
  PLAYER_PLAY: 'player/PLAY',
  PLAYER_VOLUME: 'player/VOLUME',
  // player -> server -> clients
  PLAYER_STATUS: 'status/PLAYER_STATUS',
  PLAYER_ERROR: 'status/PLAYER_ERROR',
  PLAYER_ENTER: 'status/PLAYER_ENTER',
  PLAYER_LEAVE: 'status/PLAYER_LEAVE',
  // to room (player -> server -> clients)
  EMIT_PLAYER_STATUS: 'server/EMIT_PLAYER_STATUS',
  EMIT_PLAYER_ERROR: 'server/EMIT_PLAYER_ERROR',
  EMIT_PLAYER_ENTER:  'server/EMIT_PLAYER_ENTER',
  EMIT_PLAYER_LEAVE:  'server/EMIT_PLAYER_LEAVE',
  // user
  TOGGLE_SONG_STARRED: 'server/TOGGLE_SONG_STARRED',
  LOGIN: 'user/LOGIN',
  LOGOUT: 'user/LOGOUT',
  CREATE: 'user/CREATE',
  UPDATE: 'user/UPDATE',
  GET_ROOMS: 'user/GET_ROOMS',
  ROOM_UPDATE: 'room/UPDATE',
  ROOM_CREATE: 'room/CREATE',
  ROOM_REMOVE: 'room/REMOVE',
  ROOM_EDITOR_OPEN: 'room/EDITOR_OPEN',
  ROOM_EDITOR_CLOSE: 'room/EDITOR_CLOSE',
  // misc
  _SUCCESS: '_SUCCESS',
  _ERROR: '_ERROR',
  // prefs
  PREFS_REQUEST: 'prefs/PREFS_REQUEST',
  PREFS_SET: 'prefs/PREFS_SET',
  PREFS_RECEIVE: 'prefs/PREFS_RECEIVE',
  // providers
  PROVIDER_REQUEST_PROVIDERS: 'provider/REQUEST_PROVIDERS',
  PROVIDER_RECEIVE_PROVIDERS: 'provider/RECEIVE_PROVIDERS',
  PROVIDER_REQUEST_SCAN: 'provider/REQUEST_SCAN',
  PROVIDER_REQUEST_SCAN_CANCEL: 'provider/REQUEST_SCAN_CANCEL',
  PROVIDER_SCAN_STATUS: 'provider/SCAN_STATUS',
  // ui
  HEADER_HEIGHT_CHANGE: 'ui/HEADER_HEIGHT_CHANGE',
  FOOTER_HEIGHT_CHANGE: 'ui/FOOTER_HEIGHT_CHANGE',
  SHOW_ERROR_MESSAGE: 'ui/SHOW_ERROR_MESSAGE',
  CLEAR_ERROR_MESSAGE: 'ui/CLEAR_ERROR_MESSAGE',
}
