module.exports = {
  // authentication
  SOCKET_AUTH_ERROR: 'SOCKET_AUTH_ERROR',
  // library
  LIBRARY_UPDATE: 'library/FULL_UPDATE',
  SONG_UPDATE: 'library/SONG_UPDATE',
  LIBRARY_SEARCH: 'library/SEARCH',
  LIBRARY_SEARCH_RESET: 'library/SEARCH_RESET',
  // queue
  QUEUE_ADD: 'server/QUEUE_ADD',
  QUEUE_REMOVE: 'server/QUEUE_REMOVE',
  QUEUE_UPDATE: 'queue/QUEUE_UPDATE',
  QUEUE_END: 'queue/QUEUE_END',
  // player command requests (client -> server)
  PLAYER_NEXT_REQUEST: 'server/PLAYER_NEXT',
  PLAYER_PAUSE_REQUEST: 'server/PLAYER_PAUSE',
  PLAYER_PLAY_REQUEST: 'server/PLAYER_PLAY',
  PLAYER_VOLUME_REQUEST: 'server/PLAYER_VOLUME',
  EMIT_PLAYER_STATUS: 'server/EMIT_PLAYER_STATUS',
  EMIT_PLAYER_ERROR: 'server/PLAYER_ERROR',
  // player commands (server -> player)
  PLAYER_NEXT: 'player/PLAYER_NEXT',
  PLAYER_QUEUE_END: 'player/PLAYER_QUEUE_END',
  PLAYER_PLAY: 'player/PLAYER_PLAY',
  PLAYER_PAUSE: 'player/PLAYER_PAUSE',
  PLAYER_VOLUME: 'player/PLAYER_VOLUME',
  // status
  PLAYER_STATUS: 'status/PLAYER_STATUS',
  PLAYER_ERROR: 'status/PLAYER_ERROR',
  PLAYER_LEAVE:  'status/PLAYER_LEAVE',
  // user
  SET_PREFS: 'server/SET_PREFS',
  PREFS_CHANGE: 'user/PREFS_CHANGE',
  PROVIDER_REFRESH_REQUEST: 'server/PROVIDER_REFRESH',
  TOGGLE_SONG_STARRED: 'server/TOGGLE_SONG_STARRED',
  LOGIN: 'user/LOGIN',
  LOGOUT: 'user/LOGOUT',
  CREATE: 'user/CREATE',
  UPDATE: 'user/UPDATE',
  GET_ROOMS: 'user/GET_ROOMS',
  // misc
  _SUCCESS: '_SUCCESS',
  _ERROR: '_ERROR',
}
